// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Default to the Postgres write DB from the compose files:
    // host 127.0.0.1 port 5343 maps to the `node-db-write` compose service.
    url:
      process.env["DATABASE_URL"] ??
      "postgresql://app:pass@127.0.0.1:5343/appdb",
  },
});
